//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSettingValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppSettingValue()
        {
            this.UserSettingValue = new HashSet<UserSettingValue>();
        }
    
        public int ValId { get; set; }
        public string Value { get; set; }
        public Nullable<int> IsDefault { get; set; }
        public Nullable<int> IsSystem { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SettingId { get; set; }
    
        public virtual AppSetting AppSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSettingValue> UserSettingValue { get; set; }
    }
}
