//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransfer
    {
        public long CashTransId { get; set; }
        public string TransType { get; set; }
        public Nullable<int> PosId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> AgentId { get; set; }
        public Nullable<long> InvId { get; set; }
        public string TransNum { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PosIdCreator { get; set; }
        public Nullable<byte> IsConfirm { get; set; }
        public Nullable<long> CashTransIdSource { get; set; }
        public string Side { get; set; }
        public string DocNum { get; set; }
        public Nullable<int> BankId { get; set; }
        public string ProcessType { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<int> ShippingCompanyId { get; set; }
        public Nullable<decimal> CommissionValue { get; set; }
        public Nullable<decimal> CommissionRatio { get; set; }
        public int IsCommissionPaid { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Deserved { get; set; }
        public string Purpose { get; set; }
        public bool IsInvPurpose { get; set; }
        public string OtherSide { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public Nullable<long> CreateUserId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual User User { get; set; }
    }
}
