//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryCode
    {
        public int CountryId { get; set; }
        public string Code { get; set; }
        public string Currency { get; set; }
        public string Name { get; set; }
        public byte IsDefault { get; set; }
        public int CurrencyId { get; set; }
        public string TimeZoneName { get; set; }
        public string TimeZoneOffset { get; set; }
    }
}
