//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS
    {
        public int PosId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> BalanceAll { get; set; }
        public string BoxState { get; set; }
        public byte IsAdminClose { get; set; }
    
        public virtual Branch Branch { get; set; }
    }
}
