//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramDetails
    {
        public int Id { get; set; }
        public string ProgramName { get; set; }
        public int BranchCount { get; set; }
        public int PosCount { get; set; }
        public int UserCount { get; set; }
        public int VendorCount { get; set; }
        public int CustomerCount { get; set; }
        public int ItemCount { get; set; }
        public int SaleinvCount { get; set; }
        public Nullable<int> ProgramIncId { get; set; }
        public Nullable<int> VersionIncId { get; set; }
        public string VersionName { get; set; }
        public int StoreCount { get; set; }
        public string PackageSaleCode { get; set; }
        public string CustomerServerCode { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<bool> IsOnlineServer { get; set; }
        public string PackageNumber { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsLimitDate { get; set; }
        public Nullable<bool> IsLimitCount { get; set; }
        public bool IsActive { get; set; }
        public string PackageName { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<int> PId { get; set; }
        public Nullable<int> PcdId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerLastName { get; set; }
        public bool IsServerActivated { get; set; }
        public Nullable<System.DateTime> Activatedate { get; set; }
        public Nullable<System.DateTime> PocrDate { get; set; }
        public Nullable<int> PoId { get; set; }
        public string Upnum { get; set; }
        public string Notes { get; set; }
        public string IsDemo { get; set; }
    }
}
