//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurInvoiceItem
    {
        public int InvItemId { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public int Quantity { get; set; }
        public string Notes { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public Nullable<long> ItemUnitId { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
    
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
    }
}
