//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleInvoiceItem
    {
        public int ItemTransId { get; set; }
        public int Quantity { get; set; }
        public Nullable<long> InvoiceId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public string Notes { get; set; }
        public decimal Price { get; set; }
        public Nullable<long> ItemUnitId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public decimal Profit { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal ItemTax { get; set; }
        public decimal ItemUnitPrice { get; set; }
        public decimal OfferValue { get; set; }
        public string OfferType { get; set; }
        public string OfferName { get; set; }
    
        public virtual SalesInvoice SalesInvoice { get; set; }
    }
}
