//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSettingValue
    {
        public int Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> ValId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public Nullable<int> SettingId { get; set; }
        public string Value { get; set; }
    
        public virtual AppSetting AppSetting { get; set; }
        public virtual AppSettingValue AppSettingValue { get; set; }
        public virtual User User { get; set; }
    }
}
